on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build-Payment
        run: cd service.payment/cmd && go build -v ./...
      - name: Test
        run: go test -race ./...
