on: [push]
name: Test
jobs:
  test_go:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      - name: Checkout code
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57.2
          working-directory: go
      - name: staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: 2023.1.7
          working-directory: go
      - name: Build-Payment
        run: cd go/service.payment/cmd && go build -v ./...
      - name: Test
        run: cd go && go test -race ./...
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          cd python && pytest . --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
